services:
  web:
    depends_on:
      - api
    image: magic-stream-web-dev:1.0.0
    container_name: magic-stream-web-dev
    ports:
      - "5173:5173"
    environment:
      API_URL: "http://${API_HOST_IP}:8080"

  api:
    depends_on:
      db:
        condition: service_healthy
    image: magic-stream-api-dev:1.0.0
    container_name: magic-stream-api-dev
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      ports: "8080"
      SECRET_KEY: "${SECRET_KEY}"
      REFRESH_TOKEN_SECRET_KEY: "${REFRESH_TOKEN_SECRET_KEY}"
      MONGODB_URI: "${MONGODB_URI}"
      DATABASE_NAME: "${DATABASE_NAME}"
      ALLOWED_ORIGINS: "${ALLOWED_ORIGINS}"

  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - movies:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 4

  seed:
    image: mongo:latest
    container_name: seed_mongo
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./seed:/seed-data
    command: >
      mongosh mongodb://db:27017/magic-stream-movies /seed-data/seed.js
    restart: "no"

volumes:
  movies: